### ISSUE TITLE
SkyWalking 示例中存在的问题

### ISSUE THREAD

**Issue by liangyuanpeng** [mosn/mosn-tutorial#24]
1. code失效(无法点击后在terminal执行对应命令)和代码块显示效果失效 ==>  Step1、Step4  

![image](https://user-images.githubusercontent.com/28711504/86022664-43c61000-ba5d-11ea-9e04-458f923a9031.png)
 
2. 缺少Run command (docker ps)  ==> Step1、Step2、Step3    

这是预期效果吗？  

![image](https://user-images.githubusercontent.com/28711504/86022880-87b91500-ba5d-11ea-8377-3eb6d45cecc9.png)

3.  Terminal显示的内容和预期效果似乎不一样 ==> Step2、Step3  

这是预期效果吗？  

![image](https://user-images.githubusercontent.com/28711504/86023017-b2a36900-ba5d-11ea-8374-df432fd095a2.png)

4.  dashboard 没有内容显示    

已启动容器如下图所示(执行教程中所有Run Command)  

![image](https://user-images.githubusercontent.com/28711504/86024616-c780fc00-ba5f-11ea-9b5f-7009ae7d4db3.png)

![image](https://user-images.githubusercontent.com/28711504/86024901-26467580-ba60-11ea-8dd4-38dba5b5b7e8.png)

![image](https://user-images.githubusercontent.com/28711504/86024922-2f374700-ba60-11ea-8a89-6ddae507132b.png)

**Comment by rootsongjc** [comment]
@arugal 看下这个问题吧

**Comment by rainbend** [comment]
@liangyuanpeng  感谢您的反馈，我会提交PR来修复这些问题。

**Comment by rootsongjc** [comment]
PR 已合并，但是 Step1 和 Step4 的显示仍然有问题。
https://katacoda.com/mosn/courses/istio/mosn-with-skywalking
![image](https://user-images.githubusercontent.com/3328185/87018036-4cf47100-c203-11ea-9405-c03a77bc559e.png)

**Comment by rootsongjc** [comment]
This issue has been fixed. https://www.katacoda.com/mosn/courses/istio/mosn-with-skywalking
