### ISSUE TITLE
bug: container not found

### ISSUE THREAD

**Issue by Jun10ng** [mosn/mosn-tutorial#29]
在学习[MOSN with Istio](https://katacoda.com/mosn/courses/istio/mosn-with-istio)一课中，按照课本执行以下命令会报错
kubectl exec -it $(kubectl get pod -l app=ratings -o jsonpath='{.items[0].metadata.name}')-c ratings -- curl productpage:9080/productpage | grep -o "<title>.*</title>”

<img width="1767" alt="image" src="https://user-images.githubusercontent.com/46768176/159604846-8870a829-64c6-4470-a5ac-96699a16f874.png">

**Comment by Jun10ng** [comment]
@wangfakang

**Comment by wangfakang** [comment]
> 
需要等待 bookinfo 相关的 pod 状态为 running 的时候才可以执行成功，你上面的那个报错是对应的 pod 都没有 ready。
```
controlplane $ kubectl get pods
NAME                             READY   STATUS    RESTARTS   AGE
details-v1-b5495fb97-qf9l2       2/2     Running   0          91s
productpage-v1-7c99764fb-q8hbv   2/2     Running   0          91s
ratings-v1-74d5f7ffc-wlfp7       2/2     Running   0          91s
reviews-v1-7d5444768b-kgqdk      2/2     Running   0          91s
reviews-v2-7cbb69b67b-qw2rx      2/2     Running   0          91s
reviews-v3-6479f8b-lq7rp         2/2     Running   0          91s
```

**Comment by wangfakang** [comment]
![image](https://user-images.githubusercontent.com/8215757/159618539-7bbb63f2-a3b0-4ee9-8cd2-d1120059025c.png)

**Comment by Jun10ng** [comment]
okay, thanks



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月23日(星期三) 中午11:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mosn/mosn-tutorial] bug: container not found (Issue #29)
